#pragma once

#define DGENGINE_DEFAULT_SIZE_X 320
#define DGENGINE_DEFAULT_SIZE_Y 224

#define DGENGINE_MIN_SIZE_X 320
#define DGENGINE_MIN_SIZE_Y 224

#define DGENGINE_REF_SIZE_X 320
#define DGENGINE_REF_SIZE_Y 224
